// Phase 8 — the action card. 3-5 specific moves for the buyer this week.
// Status is generated by the LLM but can be cycled locally per-deal in
// localStorage so the buyer can track their own progress between
// regenerations.

import { useEffect, useState } from 'react'

function actionHash(item) {
  return (item?.action || '').trim().toLowerCase()
}

function loadStatusOverrides(dealId) {
  try {
    const raw = window.localStorage.getItem(`klosure:buyer:playbook-status:${dealId}`)
    if (!raw) return {}
    const parsed = JSON.parse(raw)
    return parsed && typeof parsed === 'object' ? parsed : {}
  } catch {
    return {}
  }
}

function saveStatusOverrides(dealId, overrides) {
  try {
    window.localStorage.setItem(
      `klosure:buyer:playbook-status:${dealId}`,
      JSON.stringify(overrides),
    )
  } catch {
    // ignore
  }
}

const STATUS_ORDER = ['not_started', 'in_flight', 'done']
const STATUS_DOT = {
  not_started: { glyph: '○', color: 'text-navy/40' },
  in_flight: { glyph: '◐', color: 'text-amber-500' },
  done: { glyph: '●', color: 'text-emerald-500' },
}

function formatDeadline(iso) {
  if (!iso) return null
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return iso
  return d.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })
}

export default function BuyerPlaybookCard({ playbook, dealId }) {
  const items = playbook ?? []
  const [overrides, setOverrides] = useState({})

  useEffect(() => {
    setOverrides(loadStatusOverrides(dealId))
  }, [dealId])

  function cycleStatus(item) {
    const hash = actionHash(item)
    const current = overrides[hash] ?? item?.status ?? 'not_started'
    const idx = STATUS_ORDER.indexOf(current)
    const next = STATUS_ORDER[(idx + 1) % STATUS_ORDER.length]
    const newOverrides = { ...overrides, [hash]: next }
    setOverrides(newOverrides)
    saveStatusOverrides(dealId, newOverrides)
  }

  return (
    <div className="bg-white border border-navy/10 rounded-2xl">
      <div className="px-5 py-4 border-b border-navy/5 flex items-center gap-2">
        <span className="text-klo text-base leading-none" aria-hidden>✦</span>
        <h3 className="text-sm font-semibold text-navy">This week's moves</h3>
      </div>
      {items.length === 0 ? (
        <div className="px-5 py-6 text-sm text-navy/55">
          No new moves this week — Klo will add items as the deal evolves.
        </div>
      ) : (
        <ul className="divide-y divide-navy/5">
          {items.map((item, idx) => {
            const hash = actionHash(item)
            const status = overrides[hash] ?? item?.status ?? 'not_started'
            const dot = STATUS_DOT[status] ?? STATUS_DOT.not_started
            const deadline = formatDeadline(item?.deadline)
            return (
              <li key={`${hash}-${idx}`} className="flex gap-3 px-5 py-4">
                <button
                  type="button"
                  onClick={() => cycleStatus(item)}
                  aria-label={`Status: ${status.replace('_', ' ')}. Click to change.`}
                  className={`shrink-0 mt-0.5 text-lg leading-none ${dot.color} hover:opacity-70`}
                >
                  {dot.glyph}
                </button>
                <div className="flex-1 min-w-0">
                  <p className={`text-[14px] font-medium text-navy leading-snug ${status === 'done' ? 'line-through text-navy/45' : ''}`}>
                    {item?.action}
                  </p>
                  {item?.why_it_matters && (
                    <p className="text-[12px] text-navy/55 mt-0.5 leading-snug">
                      {item.why_it_matters}
                    </p>
                  )}
                  <div className="mt-1.5 flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-navy/50">
                    {item?.who && (
                      <span>
                        Who: <span className="text-navy/75">{item.who}</span>
                      </span>
                    )}
                    {deadline && (
                      <span>
                        By: <span className="text-navy/75">{deadline}</span>
                      </span>
                    )}
                  </div>
                </div>
              </li>
            )
          })}
        </ul>
      )}
    </div>
  )
}
